version: '3'
services:
  mysql8:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Hello1234
      - MYSQL_ROOT_HOST=% 
    volumes:
      - "${PWD}/mysql-sakila-db/mysql-sakila-schema.sql:/docker-entrypoint-initdb.d/1.struct.sql"
      - "${PWD}/mysql-sakila-db/mysql-sakila-insert-data.sql:/docker-entrypoint-initdb.d/2.data.sql"
    ports:
      - 53306:3306
  mariadb10:
    image: mariadb:10.6
    environment:
      - MARIADB_ROOT_PASSWORD=Hello1234
      - MARIADB_ROOT_HOST=% 
    volumes:
      - "${PWD}/mysql-sakila-db/mysql-sakila-schema.sql:/docker-entrypoint-initdb.d/1.struct.sql"
      - "${PWD}/mysql-sakila-db/mysql-sakila-insert-data.sql:/docker-entrypoint-initdb.d/2.data.sql"
    ports:
      - 43306:3306
  postgres12:
    image: postgres:12
    environment:
      - POSTGRES_PASSWORD=Hello1234
    volumes:
      - "${PWD}/postgres-sakila-db/postgres-sakila-schema.sql:/docker-entrypoint-initdb.d/1.struct.sql"
      - "${PWD}/postgres-sakila-db/postgres-sakila-insert-data.sql:/docker-entrypoint-initdb.d/2.data.sql"
    ports:
      - 55432:5432